package enterprises.iwakura.jdainteractables.components;

import java.util.UUID;
import java.util.function.Function;

import enterprises.iwakura.jdainteractables.InteractionEventContext;
import enterprises.iwakura.jdainteractables.InteractionHandler.Result;
import enterprises.iwakura.jdainteractables.InteractionType;
import lombok.RequiredArgsConstructor;
import net.dv8tion.jda.api.events.interaction.ModalInteractionEvent;
import net.dv8tion.jda.api.modals.Modal;

@RequiredArgsConstructor
public class InteractableModal extends Interactable<InteractableModal> {

    protected final String id = UUID.randomUUID().toString();
    protected final Function<ModalInteractionEvent, Result> onModalClosed;

    /**
     * Sets the modal builder to use with this interactable modal. The id of the modal builder will be set to a unique
     * id generated by this interactable modal.
     *
     * @param modalBuilder The modal builder to use
     * @return This interactable modal
     */
    public InteractableModal useModal(Modal.Builder modalBuilder) {
        modalBuilder.setId(id);
        return this;
    }

    @Override
    public Result process(InteractionEventContext ctx) {
        if (ctx.getInteractionType() == InteractionType.MODAL_SUBMITTED) {
            var modalEvent = ctx.getModalInteractionEvent();
            if (modalEvent.getModalId().equals(id)) {
                return onModalClosed.apply(modalEvent);
            }
        }
        return Result.NOT_PROCESSED;
    }
}
