package enterprises.iwakura.jdainteractables.components;

import java.util.function.Consumer;
import java.util.function.Function;

import enterprises.iwakura.jdainteractables.InteractionEventContext;
import enterprises.iwakura.jdainteractables.InteractionHandler.Result;
import enterprises.iwakura.jdainteractables.InteractionRule;
import enterprises.iwakura.jdainteractables.InteractionType;
import net.dv8tion.jda.api.events.interaction.ModalInteractionEvent;
import net.dv8tion.jda.api.modals.Modal;
import net.dv8tion.jda.api.modals.Modal.Builder;
import net.dv8tion.jda.api.requests.RestAction;

/**
 * Represents an interactable modal. Allows you to create modals that can be processed through the interaction system.
 * <p>
 * When the modal is submitted, the provided callback function will be executed to handle the modal interaction event.
 * </p><p>
 * Interactable modals ignore {@link InteractionRule}s as they can be submitted only by the user who opened the modal.
 * </p><p>
 * Interactable modals can also have an expiry time, after which the modal will no longer be interactable. The default
 * expiry time is 5 minutes, but you can change it.
 * </p><p>
 * You can also add expiry callbacks using {@link #addExpiryCallback(Runnable)} which will be called when the modal
 * expires.
 * </p>
 * After creating the interactable modal, you must register it using {@link #registerNow()} or by using {@link #registerOnCompleted()}
 * on the {@link RestAction} used to send the modal ({@link RestAction#queue(Consumer)}).
 */
public class InteractableModal extends Interactable<InteractableModal> {

    /**
     * Function to call when the modal is closed
     */
    protected final Consumer<ModalInteractionEvent> onModalClosed;

    /**
     * Constructs a new interactable modal with specified callback for when the modal is closed. You must use the
     * {@link #useModal(Builder)} method to set the modal builder to use with this interactable modal.
     *
     * @param onModalClosed The function to call when the modal is closed. The return value is ignored.
     *
     * @deprecated in favor of constructor with modal builder parameter
     */
    @Deprecated
    public InteractableModal(Function<ModalInteractionEvent, Result> onModalClosed) {
        this.onModalClosed = onModalClosed::apply;
    }

    /**
     * Constructs a new interactable modal with specified modal builder and callback for when the modal is closed.
     * Sets the id of the modal builder to a unique id generated by this interactable modal.
     *
     * @param modalBuilder  The modal builder to use
     * @param onModalClosed The callback to call when the modal is closed
     */
    public InteractableModal(Modal.Builder modalBuilder, Consumer<ModalInteractionEvent> onModalClosed) {
        this.onModalClosed = onModalClosed;
        modalBuilder.setId(this.id.toString());
    }

    /**
     * Sets the modal builder to use with this interactable modal. The id of the modal builder will be set to a unique
     * id generated by this interactable modal.
     *
     * @param modalBuilder The modal builder to use
     *
     * @return This interactable modal
     *
     * @deprecated in favor of constructor
     */
    @Deprecated
    public InteractableModal useModal(Modal.Builder modalBuilder) {
        modalBuilder.setId(this.id.toString());
        return this;
    }

    @Override
    public Result process(InteractionEventContext ctx) {
        if (ctx.getInteractionType() == InteractionType.MODAL_SUBMITTED) {
            ModalInteractionEvent modalEvent = ctx.getModalInteractionEvent();
            if (modalEvent.getModalId().equals(id.toString())) {
                onModalClosed.accept(modalEvent);
                // Always remove after processing as modals can be submitted only once
                return Result.REMOVE;
            }
        }
        return Result.NOT_PROCESSED;
    }
}
